### ISSUE TITLE
I get "loading..." instead of the expected timetable

### ISSUE THREAD

**Issue by GraRi135** [MarinescuEvghenii/MMM-Luxembourg-Public-Transport#1]
Using the folowing config:
```javascript
module: 'MMM-Luxembourg-Public-Transport',
	position: 'top_center',
	config: {
		from: "A=1@O=Assel@X=6,313529@Y=49,554448@U=82@L=210101001@B=1@p=1505823462",
		to: "A=1@O=Centre, F.D. Roosevelt@X=6,131497@Y=49,608931@U=82@L=200405013@B=1@p=1505823462",
	}
},
```
I get "loading..." instead of the expected timetable

**Comment by uxigene** [comment]
That's very strange because everything is fine for me with that config. Can you provide more info? Maybe some logs...

<img width="446" alt="screen shot 2017-09-27 at 1 50 22 pm" src="https://user-images.githubusercontent.com/5584814/30983678-67a0fb24-a48b-11e7-888e-3f62c4d28817.png">

**Comment by GraRi135** [comment]
Oddly enough It works on Ethernet for me. On wifi it wont.

I suggest you putting this module as a reuse on https://data.public.lu/en/

**Comment by uxigene** [comment]
Maybe the problem is in your internet connection? Are you sure that you have internet access thru the wifi on your device?

**Comment by GraRi135** [comment]
I host my own files for calendar and Newsfeed these both work on either wifi and ethernetI also just tested a further 3rd party modeule it doesn't work either on wifi.
Youre free to close the issue
