### ISSUE TITLE
No transport shown - Error

### ISSUE THREAD

**Issue by maxencekyz** [MarinescuEvghenii/MMM-Luxembourg-Public-Transport#2]
Hello @evghenix ,

I installed your module and put the config below:

> 	{
			module: 'MMM-Luxembourg-Public-Transport',
			config: {
				from: "A=1@O=Belair, Place de France@X=6,106759@Y=49,606540@U=82@L=200403013@B=1@p=1615358928;",
		        to: "A=1@O=Rollingergrund, Bei der Fiels@X=6,114337@Y=49,617219@U=82@L=200425003@B=1@p=1615358928;",
				maxLength: 5,
				fetchInterval: 6000,
			}
		},

However, i see nothing on my screen because the console is saying:

> Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Class.normalize (MMM-Luxembourg-Public-Transport.js:99)
    at Class.socketNotificationReceived (MMM-Luxembourg-Public-Transport.js:91)
    at module.js:250
    at Socket.<anonymous> (socketclient.js:39)
    at Socket../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)
    at Socket.emitEvent (socket.js:264)
    at Socket.onevent (socket.js:251)
    at Socket.MMSocket.self.socket.onevent (socketclient.js:33)
    at Socket.onpacket (socket.js:215)
    at Manager../node_modules/component-emitter/index.js.Emitter.emit (index.js:145)

![image](https://user-images.githubusercontent.com/80335419/111062999-a4429380-84ac-11eb-9c46-c0dfb8d5e872.png)

Any idea, about how to solve this problem ?
Thanks and have a nice week-end :)))
- Max

**Comment by uxigene** [comment]
Hello @maxencekyz. For some reason the API does not return the schedule. Don't know why. Maybe the API got changed but I see nothing in the docs https://data.public.lu/en/datasets/departs-en-temps-reel-ancienne-api

I have tried to rename the parameter "direction" to "location" in and it returns the schedule, but I'm not sure if it's right. Probably it returns all the buses in that location. Could you please check that?

Here is the place where you can rename the parameter: 
https://github.com/evghenix/MMM-Luxembourg-Public-Transport/blob/master/MMM-Luxembourg-Public-Transport.js#L13

**Comment by maxencekyz** [comment]
Thanks for the quick reply @evghenix 
I tried to change "direction" to "location" in line 13. I don't have any errors from the console anymore.
However, I still don't see anything on my mirror..

**Comment by evghenix** [comment]
Got it. I have to dig into it deeper. I think the main reason is some API changes. But due lack of documentation it's hard to understand what is going on. I'll try to check it ASAP.

**Comment by uxigene** [comment]
I can suggest you to try figuring out your locations by using the following api:

http://travelplanner.mobiliteit.lu/hafas/query.exe/dot?performLocating=2&tpl=stop2csv&stationProxy=yes&look_maxdist=150&look_x=6106759&look_y=49606540

Here you need to play with look_x and look_y params, those are latitude and longitude coordinates. It will return you exact location id. Also look_maxdist parameter might be useful, increasing or decreasing it will give you more or less location ids. And after try to play with the following API by putting your parameters:
http://travelplanner.mobiliteit.lu/restproxy/departureBoard?accessId=cdt&format=json&id=A=1@O=Belair,%20Place%20de%20France@X=6,106759@Y=49,606540@U=82@L=200403013@B=1@p=1615358928

Note: in the example above direction parameter is omitted, so, most probably it returns all departures from that location. You need to play with direction parameter and find why it returns nothing in your case.

As soon you get an appropriate response we can analyse the data and fix it.

PS: Please recheck your departure location id and destination location id. It might happen that you put wrong stations and there are no transport for them. (EX: you choose a bus stop but wrong direction on opposite side)

**Comment by uxigene** [comment]
I've tried to make the request according to your config and there is no result for that criteria:

http://travelplanner.mobiliteit.lu/restproxy/departureBoard?accessId=cdt&format=json&id=A=1@O=Belair, Place de France@X=6,106759@Y=49,606540@U=82@L=200403013@B=1@p=1615358928&direction=A=1@O=Rollingergrund, Bei der Fiels@X=6,114337@Y=49,617219@U=82@L=200425003@B=1@p=1615358928

But, as you can see in the request bellow, it works with other "direction" parameter:

http://travelplanner.mobiliteit.lu/restproxy/departureBoard?accessId=cdt&format=json&id=A=1@O=Belair, Place de France@X=6,106759@Y=49,606540@U=82@L=200403013@B=1@p=1615358928&direction=A=1@O=Hamilius (Tram)@X=6,126230@Y=49,611170@U=82@L=300029002@B=1@p=1615358928

I'm suggesting you to double check the stops ids.

**Comment by uxigene** [comment]
I think I now the reason why there are no results for you. Probably you don't have a direct transport from your location to final destination. If that's true try using as a "direction" parameter the location where you change the bus.

**Comment by uxigene** [comment]
@maxencekyz any updates?

**Comment by maxencekyz** [comment]
Hello @evghenix , i don't have my magic mirror with me.
Let me try in few days and keep you updated :)

Thanks for your support !

**Comment by maxencekyz** [comment]
Hello @evghenix,

That's what the issue, thank you !
I just used wrong id.

Have a good day and an amazing week, well appreciate your support ! :)
