### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by Cmachtel** [MarinescuEvghenii/MMM-Luxembourg-Public-Transport#3]
Does currently not work anymore

**Comment by uxigene** [comment]
@Cmachtel could you please provide more details?

**Comment by Cmachtel** [comment]
Hy, 
The API Webpage does not exist anymore or has changed place. Additionaly it seams not working on MM2 but this can also be done due to API changes. Would be happy to use it and maybe help in putting it again up to date

**Comment by uxigene** [comment]
@Cmachtel looks like the API is not available. It returns 503 error. I couldn't find any information about moving it somehere alse. Let's hope this is temporarry issue on their side.

**Comment by Cmachtel** [comment]
No, it is like this since a few months :-(
The talk about a new interface over https://www.mobiliteit.lu/fr/services/mconcept/ but i could not get more information for now. maybe if you contact them and tell them what exactly is needed

**Comment by Cmachtel** [comment]
I have done some search and the new api is explained here: https://data.public.lu/fr/datasets/api-mobiliteit-lu/

**Comment by uxigene** [comment]
An update was merged. Now it should work with new API.
