### ISSUE TITLE
Create package.json

### ISSUE THREAD

**Issue by KristjanESPERANTO** [MarinescuEvghenii/MMM-Luxembourg-Public-Transport#5]
I am working on a new module list, which you can see [here](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/). If you search for your module in it, you will see that it looks a bit bland at the moment, as a screenshot and tags are missing.

You can change that by adding a `package.json` file. The information that is currently used from that file is the license information (the screenshot can only be displayed if the license is free) and the keywords (these are then displayed as tags).

[Here is an example of a package.json](https://github.com/Jacopo1891/MMM-RandomQuotes/blob/master/package.json).

I recommend using the keyword "Public Transport", because it's like a main category.

It would be nice if you would add the file to your repository :slightly_smiling_face:

**Comment by uxigene** [comment]
@KristjanESPERANTO thanks for the message. Added package.json file.

**Comment by KristjanESPERANTO** [comment]
Thanks! Your module now looks nice in the new list! :rocket: :smiley:
